### ISSUE TITLE
[Tracking ticket] In the next 30 days, how we'll onboard 100 volunteers as Mozilla Club Captains

### ISSUE THREAD

**Issue by thornet** [mozilla/learning-networks#200]
July 10: 
- [x] Scripts for an interview are created. [#193 @soapdog] 
- [x] Make a tutorial about how to use Central Station [ #203 @thornet]
- [x] Staff emails all Regional Coordinators. [#205 @thornet]

July 17: 
- [x] Staff Organizers call their RCs: [ @simonaramkisson @ldecoursy @Saallen @amirad @thornet @soapdog ]
- Review Central Station, inc. how to change website state column.
- Confirm assigned clubs 
- Practice the interview script
- [x] The welcome guide and pledge contract is created. [#201 @amirad]
- [x] The email templates for scheduling the interviews are finalized. [ #204 @amirad] 

July 24: 
- [x] Regional Coordinators email Club Captains and schedule interviews.
- [x] Staff assigns any remaining Club Captains to Regional Coordinators. [ @simonaramkisson @ldecoursy @Saallen @amirad @thornet @soapdog ]

July 30: 
- [x] Interviews are underway.
- [ ] The guide and pledge/contract is sent to Club Captains.

August 7: 
- [ ] All interviews are done. 
- [ ] The list of Club Captains that signed the contract is confirmed.
- [ ] RC confirms with their Staff Organizer if they want to continue the relationship with the Club Captain. If not, Staff Organizer re-assigns. 

Success is: By August 7, 100 people interviewed and pledged to host at least 3 Mozilla Club sessions by Mozfest.

Scope/constraints: Club Captains have a relationship with regional coordinators.

Notes from Whistler session: https://docs.google.com/document/d/1H-jB9DS_JARjldb5SlTOfnlHdT5VvR8NtTudzt_qMFY/edit

**Comment by hannahkane** [comment]
Taking this out of the July 10th milestone, so we can close the milestone.

**Comment by thornet** [comment]
@simonaramkisson @ldecoursy @Saallen @amirad @soapdog did you get a chance to have a 1:1 with all of your RCs? 

This week we'll pick up any potential club captains not yet assigned to an RC.

**Comment by amirad** [comment]
Yes, I've 1-1 with all my RCs and just added my name to a few clubs to try and interview!

**Comment by Saallen** [comment]
I have had my 1:1 with dorine but now I am picking up new cc on central station- I will interview this week and post holiday if that is gravy :shaved_ice:

**Comment by thornet** [comment]
Update: I imported about 40 new clubs and just sent them the email interview. Will compare results.

**Comment by amirad** [comment]
Completed.
