### ISSUE TITLE
[Tracking Ticket] Scope a "tiered" offering for Mozilla Clubs

### ISSUE THREAD

**Issue by thornet** [mozilla/learning-networks#216]
# Context:

Since initiating the Mozilla Clubs program, we have seen a lot of interest. We also know from early feedback and research that 1:1 volunteer-volunteer relationships increase the quality and alignment of a club. And there's a limit to our current volunteer capacity (Regional Coordinators), which is intentional. 

More: http://michellethorne.cc/2015/07/mozilla-clubs-2015-half-time-report/
# Problem Statement:

How do we ensure that as many interested educators & activists as possible benefit from our web literacy and club offering, while ensuring that the high quality / engagement / sustainability of Mozilla Clubs continues? 
# Possible Tactic:

Develop a "tiered" offering to guides club captains along a spectrum of commitment. Note that this is not an obligatory progression -- it is more about what level of engagement a club captain wants and matching that with what our program has the capacity to offer. 
# Timeline

August 7:
- [ ] Scope problem statement
- [ ] Get feedback from clubs staff
- [ ] Document motivations and possible benefits for engaging at different tiers

August 14: 
- [ ] Share progress with RCs and get feedback
- [ ] Write up light-weight public documentation about the tiers
- [ ] Review with legal

August 21:
- [ ] Tighten messaging in email and website copy to reflect offering
- [ ] Circulate the tiered offering to clubs already in the pipeline (see #200)
- [ ] Test and analyze responses  

August 28: 
- [ ] Refine copy on teach.mozilla.org and in supporting docs
- [ ] Onboard next cohort of RCs with knowledge of the tiered offering

cc @amirad @ldecoursy @Saallen @simonaramkisson @soapdog @chrislarry33 @hannahkane

**Comment by anmechung** [comment]
Totally agree that 1:1 volunteer-volunteer relationships increase the quality and alignment of a club. In addition, there may be a group/type who may not need this as much. How about an option/alternative where we can on-board RCs and CCs through in-person train the trainers (i.e. 25-100 people) with partners who do professional development well such as MOUSE?

**Comment by hannahkane** [comment]
FYI: Adding August 28 publish date to MLN site roadmap: http://etherpad.io/teach

**Comment by amirad** [comment]
I'm going to close this since it's already happened and broken out into other tickets.
