### ISSUE TITLE
[Tracking ticket] On-board 15 more RCs by Sept 8

### ISSUE THREAD

**Issue by thornet** [mozilla/learning-networks#219]
Volunteer role posted here: http://mozilla.github.io/learning-networks/clubs/regional-coordinator.html
- [ ] Reach out to the fellows programs if they have candidates 
- [ ] Publish position posting on listserv, etc. 
- [ ] Contact our RCs again for their recommendations 
- [ ] Scope what an RC "light" looks like: online moderation of more clubs, less intense 1:1 interaction

What else?
cc @amirad @Saallen @ldecoursy @soapdog @simonaramkisson

**Comment by ldecoursy** [comment]
Closing - onboarding for 17 new RC's starts this week!
