### ISSUE TITLE
[Tracking ticket] Back-to-School Thimble activities

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#224]
Review Back to School Activities
- [x] Review existing activies (cc @hannahkane, @ldecoursy)
- [x] Draft any necessary copy, makes
- [x] Mirgrate drafts to Thimble
- [x] Get feedback (cc @anmechung, @chrislarry33)
- [x] Revise
- [x] New Thimble launches

[Back to the meta.](https://github.com/mozilla/learning-networks/issues/233)

**Comment by jgmac1106** [comment]
In an earlier curriculum ticket (issue #45)  we thought about having a print stylesheet. I clicked on print and it wasn't bad but it would be nice if a print stylesheet deprecated the formatting of the unorganized list and did not include any images.

**Comment by jgmac1106** [comment]
I have never done anything with javascript so I took a look at the postcard activity. I think the key definitions are good. 

I would to like to have learned more about the function. Even if it is just for context. I am currrently just switching the words in javascript. What does the function do?

Also I wonder about linking to different Google Fonts and if that unnecessarily complicates things. I might go with a font family.

**Comment by jgmac1106** [comment]
I also think we have way too many learning objectives for each teaching kit. Yes you will have to do all 6-7 objectives  but that does not mean the educator should focus on those in terms of what she is trying to measure in terms of learner growth.

I would try to hone in on what they key lesson that make is trying to teach.

**Comment by chadsansing** [comment]
Great feedback moving forward. It's definitely a challenge to think about what - and how much - to surface where in terms of objectives and instructional copy and to have objectives that reflect what learners do in the activity. An explainer comment for the function would be great, as well. 

I know feedback on these makes will help us refine instruction in future makes and help us with teaching new Thimble features, too.

**Comment by jgmac1106** [comment]
Oh yeah nothing as a roadblock in terms of shipping the activities. They
are good to go in terms of objectives. In the future we should think about
what is the key take away. For postcards for example you are changing a
variable in the array.

The postcard activity has all the css in the index file. Should this be
pulled into a stylesheet file?
The post card activity has both inline html comments and the tutorial. Do
we want both or either?

The comic book activity has all the css in the index file. Should these be
in a separate file?

**Comment by chadsansing** [comment]
First, let me say the new Thimble UI and features are awesome and facilitate so much good practice. I am excited! (cc @hannahkane)

In thinking of user-testing w/ the gamut of middle school kids I've taught, I recommended that we ship at least a few activities with the CSS and .js on the index.html pages. I think adding file-directory organization to introductory activities without actual file-directory activities presents a barrier to entry for kids not yet there with organization. I'm thinking of organizational readiness like algebra readiness. Some kids will be there on day one; some will not; start with one-pagers; add complexity later _and_ teach the complexity explicitly.

Not sure novice teacher users would all be there, either.

Thinking that having everything on one page concretizes the connections between HTML, CSS, and .js, so those connections aren't lost in abstractions once the CSS and .js live elsewhere.

I agree, of course, that separate files are best practice and I know we'll work toward teaching the how and why in future materials.

**Comment by jgmac1106** [comment]
WFM, and you are right Thimble rocks.

When I beta tested and asked teachers to start their own projects they got
tripped up when trying to link back to their stylesheet. They were opening
up projects on old thimble and trying to copy and paste so a make with one
file structure makes sense.

Though I would argue I wouldn't do this for the .js make. If you are ready
to level up your .js skills you are probably familiar with file-directories.

I think all three are ready to ship but wanted to leave feedback. Another
thing I think we should consider is including links back to MDN articles
where appropriate and if the articles are developed. This could be a want
to learn more about Functions? Check out this resource....since the .js
make only went over switching variable in the array.

**Comment by jgmac1106** [comment]
I also had a random thought on curriculum testing after watching the A/B
testing being done on the CTA. Could a tool like optimizely (or something
similar) test out, for example, one make with inline html comments as a
tutorial and one make with the tutorial pages and track if either a make
was finished or the time it took to complete a project?

Thinking about Richard Mayer's work and multimodal learning. He tested
about every variable under the sun from font placement, to color, etc. This
probably doesn't belong in this ticket at all (I couldn't find the measure
learning on Thimble ticket) but the CTA testing sparked the idea of how can
we get past costly cognitive labs.

**Comment by chadsansing** [comment]
+1 MDN & parallel development/testing. I'd like to explore lots of yes/and pathways across MLN.
