### ISSUE TITLE
[Tracking ticket] Review JS module

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#226]
- [x] [Review JS module](https://github.com/mozilla/learning-networks/issues/173#issuecomment-124646697). (cc @mickfuzz, @thornet)
- [x] Draft feedback.
- [x] Get feedback. (@ldecoursy, @chrislarry33)
- [x] Report next steps.

**Next steps**
- [x] Get feedback/context from @omnignorant.
- [x] Proof activities.
- [x] Coordinate w/ @hannahkane to post to /activities.

[Back to the meta.](https://github.com/mozilla/learning-networks/issues/233)

**Comment by thornet** [comment]
awesome tracking tix! ＼（＾▽＾）／

On Wed, Aug 26, 2015 at 2:48 PM, Chad Sansing notifications@github.com
wrote:

> - Review JS module
>   https://github.com/mozilla/learning-networks/issues/173#issuecomment-124646697.
>   (cc @mickfuzz https://github.com/mickfuzz, @thornet
>   https://github.com/thornet)
> - Draft feedback.
> - Get feedback. (@ldecoursy https://github.com/ldecoursy,
>   @chrislarry33 https://github.com/chrislarry33)
> - Report next steps.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/learning-networks/issues/226.

## 

_Michelle Thorne_
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by chadsansing** [comment]
@hannahkane, can we get this kit 

http://mozilla.github.io/webmaker-curriculum/QuackingJavascript/

posted on /activities underneath the CSS module?

cc @thornet, @mickfuzz

**Comment by hannahkane** [comment]
Yes! But under which module? The CSS Story Cards one?

Also, will need:
- Title
- Level
- Developed by (with link to Twitter or whatever)
- Brief description
- Image

**Comment by chadsansing** [comment]
Thanks, @hannahkane!

Yes, this module should be listed under the CSS story cards module.
1. Quacking JavaScript
2. JavaScript beginners
3. Developed by [Mick Fuzz](https://courses.p2pu.org/en/mickfuzz/)
4. Learners get familiar with writing Javascript in this fun, five-part module. Together we discover the foundations of the text coding by being creative and making our own web pages. 
5. Image: http://mozilla.github.io/webmaker-curriculum/QuackingJavascript/images/rubberduck_square.jpg

Do those work?

**Comment by mickfuzz** [comment]
Great stuff, I've just started being a part of Manchester Hive - so let's put that at the authour instead of me and I'll do a blog post about it there.
http://hivemanchester.net/

@hannahkane @thornet @LauraHilliger  
- Let me know if there are more things I should do to get this ready. It still feels a bit rough to me in parts. But I'm happy to work iteratively on it too.

**Comment by thornet** [comment]
＼（＾▽＾）／

On Mon, Sep 14, 2015 at 4:04 PM, mickfuzz notifications@github.com wrote:

> Great stuff, I've just started being a part of Manchester Hive - so let's
> put that at the authour instead of me and I'll do a blog post about it
> there.
> http://hivemanchester.net/
> 
> @hannahkane https://github.com/hannahkane @thornet
> https://github.com/thornet @LauraHilliger
> https://github.com/LauraHilliger
> - Let me know if there are more things I should do to get this ready.
>   It still feels a bit rough to me in parts. But I'm happy to work
>   iteratively on it too.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/learning-networks/issues/226#issuecomment-140085662
> .

## 

_Michelle Thorne_
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by hannahkane** [comment]
Yup. Will put it in the heartbeat that starts today: https://github.com/mozilla/teach.webmaker.org/issues/1255

**Comment by hannahkane** [comment]
Quacking Javascript is now live on https://teach.mozilla.org/activities
