### ISSUE TITLE
[Tracking ticket] Review curriculum queue

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#227]
- [x] Review [queue](http://mozilla.github.io/webmaker-curriculum/) materials & sequencing
- [x] Draft feedback.
- [x] Get feedback. (@ldecoursy, @chrislarry33)
- [x] Report next steps.

**Next steps**
- [x] Continue discussions w/ @ldecoursy & @hannahkane.
- [x] Blog re: curriculum thinking.
- [x] Develp Q3/Q4 Curriculum Roadmap (future ticket).

[Back to the meta.](https://github.com/mozilla/learning-networks/issues/233)
