### ISSUE TITLE
[Tracking ticket] Review HIVE portfolios to surface possible MLN curriculum

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#228]
- [x] Review HIVE portfolios (NYC, Chicago, Pittsbrugh, Toronto, Chattanooga).
- [x] Draft feedback.
- [x] Meet w/ Leah & Julia. (cc Leah, Julia)
- [x] Get feedback. (cc @ldecoursy, @chrislarry33)
- [x] Report next steps.
- [x] Meet w/ Lindsey, Kathryn, & Ani  & Simona (cc @LindseyFrost, @KathrynMeisner, @simonaramkisson, & Ani)
- [x] Draft feedback.
- [x] Get feedback.
- [x] Report next steps.

**Next Steps:** ship recommendations to Chris & Lainie; work with Hive organizers to identify areas of 'heat' and curate and support partners and activities that complement work in the Curriculum Queue.

[Back to the meta.](https://github.com/mozilla/learning-networks/issues/233)
