### ISSUE TITLE
[Tracking ticket] Review TLM materials

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#229]
- [x] Review TLM materials.
- [x] Draft feedback.
- [x] Get feedback. (cc @anmechung, @amirad, Sam, Leah)
- [x] Report next steps.

**Next Steps**
- [x] Blog re: curriculum thinking.
- [x] Consult on development of TLM materials w/ @zee-moz in Open Science and Participation team.
- [x] Work into Q3/Q4 Curriculum Road Map (future ticket).

**Materials**
- [Curriculum spreadsheet](https://docs.google.com/spreadsheets/d/1VHj-89BhI4HtUQfXOW9jKlSGLx-FXV9Er1G86HKvtZU/edit#gid=0)
- [Design work](https://github.com/mozilla/teach.webmaker.org/issues/1156)
- [Git book](http://laurahilliger.gitbooks.io/teach-like-mozilla/)
- [MoPad](https://teach.etherpad.mozilla.org/tlmcontent)

cc @zee-moz

[Back to the meta.](https://github.com/mozilla/learning-networks/issues/233)

**Comment by hannahkane** [comment]
So glad you're taking this on. Just want to make sure you've seen some initial wireframing that was done: https://github.com/mozilla/teach.webmaker.org/issues/1156

Don't feel like we need to stick with that, though. We did it, in part, as a design exercise, so it's definitely up for lots of revisions if needed.

**Comment by amirad** [comment]
Excited your picking this up! Let us know if you want us to dig up other old resources that you can review.

**Comment by chrislarry33** [comment]
Where are the materials collected?

**Comment by hannahkane** [comment]
@chrislarry33 - this is one place: https://teach.etherpad.mozilla.org/tlmcontent

**Comment by amirad** [comment]
There's also this http://laurahilliger.gitbooks.io/teach-like-mozilla/

**Comment by jgmac1106** [comment]
The TLM calls were also combined with the last curriculum calls. I tried to
hunt them down but could not find them. I noted in another ticket that Emma
Irwin is doing something very similar for participation. It is almost
undistinguishable to what we were trying to do with TLM.

**Comment by chrislarry33** [comment]
Thanks all!

**Comment by chadsansing** [comment]
I'm also looking here: https://docs.google.com/spreadsheets/d/1VHj-89BhI4HtUQfXOW9jKlSGLx-FXV9Er1G86HKvtZU/edit#gid=0.

Will gather the links into the ticket, as well.

**Comment by jgmac1106** [comment]
Here is some stuff I found: 
https://teach.etherpad.mozilla.org/openfluency
https://github.com/mozilla/teach.webmaker.org/issues/27#issuecomment-88318562
http://quickthoughts.jgregorymcverry.com/2015/reflection-on-the-teachtheweb-mozteach-curriculum-call
http://quickthoughts.jgregorymcverry.com/2015/open-web-leadership-and-teachtheweb

This is the link on the leadership development curriculum MoPa is working on: https://docs.google.com/document/d/1OE4Od4TgLo-90eDuv9Np4PZK9VZoZLUhIg0H9V-LSeU/edit#

While the content would shift for TLM there is a lot of overlap (to the point I thought TLM was handed off to a different repo). I really like the five foundational attributes. There might be some benefit to using the same attributes across TLM.

**Comment by chadsansing** [comment]
Thanks, @jgmac1106!
