### ISSUE TITLE
[Tracking ticket] Develop curriculum & community contribution guidelines

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#230]
- [x] Draft criteria & descriptor headings.
- [x] [Get feedback on criteria & descriptor headings](https://github.com/mozilla/learning-networks/issues/222). (cc @hannahkane, @amirad, @KevZawacki, @anmechung, @jgmac1106, @ldecoursy, @chrislarry33)
- [x] Revise headings.
- [x] Draft definitions & criteria copy.
- [x] Get feedback on definitions & criteria copy. (cc ibid)
- [x] Revise definitions & criteria copy.
- [x] Share doc for feedback.
- [x] Report on next steps.

**Next steps**
- [x] Revise by 9/11/15.
- [x] Test (future ticket).
- [x] Recommend how to use the developed criteria.
- [ ] Get a DARCI on production and shipping of internal & external user-facing criteria (future ticket).

[Back to the meta.](https://github.com/mozilla/learning-networks/issues/233)

**Comment by chadsansing** [comment]
Help with light definitions of criteria row headers greatly appreciated.

**Comment by jgmac1106** [comment]
I think Quality should go. That is the point of the matrix. To place the quality of the submission on a scale. When you read "quality" descriptors they sound more procedural. Its like where the curriculum currently resides in the cue rather than a judgement of its content.

I also think "tone" overlaps too much with other criteria.  The fewer criterion we have the more succinct difference in scales will be for the users.

I know we are leaving pedagogy as open as possible to allow pathways to emerge rather than be dictated but we may want to be more specific for the non-educators. It seems all the teaching kits have a "primary goal" of making the project and the traditional learning objectives. The rubric should speak to this. 
- The materials contains both a project goal and 2-3 primary learning objectives and series of activites that provide evidence of reaching the goal by mastering the objectives.

Is that too much edu jargon?

**Comment by chadsansing** [comment]
I'll push back on quality. I think we want contributors to think about testing and documenting their work, especially within the clubs framework. Open QA is a part of our process that we should educate community members about so they can adopt Open QA practices appropriate to their work (e.g. a teacher should have an idea of which activities hit or miss and stop using the ones that miss just because they are there). I would also want it to be clear that QA is an open process, not an editorial gatekeeper, so I'd rather it be articulated and in the open.

**Comment by chadsansing** [comment]
I'll push back on tone, also, which we've collapsed into equity as per your suggestion, @jgmac1106. If we lead with our values, and if our rubric leads community development in any way, I think it needs an equity/tone piece. The rubric isn't for every make or kit or activity, but for helping community members understand how to develop pieces for adoption into curriculum or curation on MLN channels. If we're talking the difference between 4 and 5 criteria, and 4 means we ditch equity/tone, I'd encourage us to go with 5.

**Comment by chadsansing** [comment]
I like the objectives language and have pasted it into the doc for feedback. Thanks, @jgmac1106!

**Comment by jgmac1106** [comment]
I was suggesting I thought tone fit in as a part of equity not as a jettison of the ideas.

In terms of quality thanks for the clarification. I was thinking of quality in terms of a judgement (which is the purpose of a rubric) versus a process (like Quality Assurance). Maybe just be explicit and call the criteria Quality Assurance...but I am fine either way.

**Comment by chadsansing** [comment]
Will do, re: QA. Is the Equity criterion working better now, @jgmac1106?

**Comment by chadsansing** [comment]
Sharing on team call, 9/2/15.

**Comment by chadsansing** [comment]
Sharing revisions, new docs on team call, 9/9/15.
