### ISSUE TITLE
[Tracking ticket] Surface future curricular opps from new & emergent community resources

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#231]
- [x] Check in re: Webmaker. (cc Matthew)
- [x] Check in re: new Thimble. (cc @davidascher) - scheduled
- [x] Check in re: L10n. (cc @soapdog) - scheduled
- [x] Check in re: GitHub.
- [x] Report next steps.

**Next steps:** participate in demo calls/community and bake-in connections to these projects (and MDN) into curriculum content and templates.

[Back to the meta.](https://github.com/mozilla/learning-networks/issues/233)
