### ISSUE TITLE
[Tracking ticket] Develop/steward MLN community 'curricular ops' sharing practices

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#232]
- [x] Help w/ new community call work
- [x] Establish sharing practices w/ curriculum/instructional developers across MLN
- [x] Report on next steps.

**Next steps:** weekly Curricular Ops call w/ @zee-moz established; participate in community call relaunch (future ticket).

[Back to the meta.](https://github.com/mozilla/learning-networks/issues/233)

**Comment by chadsansing** [comment]
Established weekly Curricular Ops call w/ @zee-moz: Tuesdays at 1PM ET.
