### ISSUE TITLE
[Meta] [Tracking ticket] Curriculum review projects

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#233]
This is largely a work-in-the-open, self-tracking and reporting ticket, but feel free to offer feedback on any of the work below.

**Responsible**: Chad

**cc**  @ldecoursy, @chrislarry33, @hannahkane, @thornet, @omnignorant
- [x] [Review back-to-school Thimble activities](https://github.com/mozilla/learning-networks/issues/224). (cc @anmechung)
- [x] [Review shipped templates & embdedded practices](https://github.com/mozilla/learning-networks/issues/225).
- [ ] [Review JS module](https://github.com/mozilla/learning-networks/issues/226). (cc @mickfuzz)
- [x] [Review curriculum queue](https://github.com/mozilla/learning-networks/issues/227).
- [x] [Review](https://github.com/mozilla/learning-networks/issues/234) [accessibility module](https://github.com/mozilla/learning-networks/issues/214). (cc @smithisgeneric)
- [x] [Review HIVE portfolios](https://github.com/mozilla/learning-networks/issues/228). (cc Leah, Julia)
- [x] [Review TLM work](https://github.com/mozilla/learning-networks/issues/229). (cc @anmechung, @amirad, Sam, Leah)
- [x] [Develop curriculum & contribution guidelines](https://github.com/mozilla/learning-networks/issues/230). (cc @KevZawacki, @amirad, @anmechung, @jgmac1106)
- [x] [Surface future curriculum dev opps](https://github.com/mozilla/learning-networks/issues/231), especially re: new and/or emergent community ops resources, e.g. GitHub, new Thimble, Webmaker, L10n. (cc @soapdog, @davidascher, Matthew)
- [x] [Develop/steward MLN, community 'curricular ops' sharing practices](https://github.com/mozilla/learning-networks/issues/232) (cc @zee-moz)

**Comment by jgmac1106** [comment]
+1 nice job

**Comment by jgmac1106** [comment]
I didn't know where best to file this so I am putting it under this ticket. In Basics I module, I keep returning to the web chef, and tell us your story activities.

I tried them last year. I think they are simply too big to be an activity within a kit and could be kits themselves. I think they are great activities and we should flesh the out more into kits.

The content also needs an update as it often refers to "webmaker"

**Comment by mickfuzz** [comment]
Is the webmaker term deprecated? I've been busy so maybe didn't get the memo.

**Comment by jgmac1106** [comment]
Sorry, let me clarify. I meant webmaker being used at the nomenclature for the relaunched Mozilla Learning Networks versus referring to the webmaker app that is part of MLN.

I like the idea of the capstone activities Web Lit Basics I. Just worry that the two we published are too involved.

May be awhile before we get to revisit Web Lit Basics I but cnce the RCs and CC get rolling using the curriculum it might be something to watch.

**Comment by chadsansing** [comment]
Closing. Look to current/future curriculum [meta] tickets.
