### ISSUE TITLE
[Tracking ticket] Review accessiblity module

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#234]
- [x] Review accessibility module (cc@thornet, @smithisgeneric)
- [x] Draft feedback.
- [x] Get feedback. (cc @ldecoursy, @chrislarry33)
- [x] Report next steps.

**Next steps:** look for places to plug this activity into in future modules.

[Back to the meta.](https://github.com/mozilla/learning-networks/issues/233)
