### ISSUE TITLE
[Meta] Curriculum Work, 9/14/15 - 9/25/15

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#240]
**Meta**
- [x] Close previous tracking ticket.
- [x] Draft next tracking ticket for next two weeks.

**Curriculum**
- [ ] Test and suggest use cases for curriculum rubric and contribution guidelines. (cc @hannahkane, @ldecoursy, @chrislarry33, @amirad, @omnignorant, @jgmac1106)
- [x] Evaluate Hungercraft activities (cc Leah, @ldecoursy, @chrislarry33).
- [x] Share "Children's games that teach the web" prototypes. (cc @amirad)
- [ ] ~~Recruit informal advisory committee of internal and external stakeholders for early dev curriculum content & template feedback and testing (cc @chrislarry33, @ldecoursy)~~
- [x] Stay involved with community call reboot work (cc @ldecoursy)
- [ ] Reboot curriculum queue. (cc @ldecoursy)
- [x] Decide on structure of LRNG Web Lit curriculum and badge offering.
- [x] Develop questions for Thimble Twitter chat.
- [ ] Get Webmaker module up.
- [x] Collect, polish, & ship privacy, security, & policy module.
- [ ] Back-to-School Kit.
- [x] Add intros to Discourse Curriculum category pages.

**Clubs**
- [x] Share new curriculum pieces on RC call.

**Teach Like Mozilla**
- [x] Draft copy for TLM horizontal site.
- [ ] Continue 2015-16, p2 TLM module development re: scale & spread w/ Leah (cc Leah)

**Hive**
- [ ] Continue 2015-16, p2 TLM module development re: scale & spread w/ Leah (cc Leah)

**Trainings**
- [x] NWPAM training planning sprint

**L10n**
- [x] Develop DARCI & plan for L10n Web Lit localization campaign. (cc @chrislarry33, @ldecoursy , @soapdog, @amirad, @KevZawacki)

**MozFest**
- [x] Submit MozFest pathway proposal. (cc Sam)
- [x] Pathway potential sessions.
- [x] Milestone accepted sessions.
- [ ] Send notices re: acceptance.

**Leadership group**
- [x] Help w/ SWOT? (cc Sam)

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by chadsansing** [comment]
Struck through some items that might need moved.

**Comment by chadsansing** [comment]
TLM work & production moved ahead to [issue #249](https://github.com/mozilla/learning-networks/issues/249).
