### ISSUE TITLE
[Meta] Curriculum work, 9/28/15 - 10/9/15

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#249]
**Meta**
- [x] Close previous tracking ticket.
- [x] Draft next tracking ticket.

**Curriculum**
- [x] Identify a piece of work to demo.
- [ ] Report on curriculum rubric & guidelines testing. (cc MozTeach, @soapdog, @omnignorant, @thornet)
- [ ] Set up more rubric & guidelines testing. Ask for RC and CC feedback re: guidlines on Discourse. (cc @ldecoursy)
- [x] Watch Back-to-School Write the Web module production. (cc @hannahkane)
- [x] Watch Webmaker module production (cc @hannahkane)
- [x] Iterate on Expanded Privacy Kit toward production (cc @chrislarry33, @hannahkane)
- [x] Watch Curriculum Queue re-boot/production (cc @hannahkane, @ldecoursy)
- [x] Blog on what I've learned so far & wish I could take back in time to my classroom. (cc @chrislarry33, @ldecoursy, @kevzawacki)
- [x] Work towards a community call/tweetchat/hangout. (cc @ldecoursy)
- [ ] Find some time & co-conspirators for exploratory design.

**Clubs**
- [x] Scope & begin prototyping towards a Web Lit Basics II module. (cc @amirad)

**Teach Like Mozilla**
- [x]  Scope & begin prototyping toward an initial Scale & Spread module. (cc @leahatplay)

**Hive**
- [x] Support partners' Hungercraft work (cc @leahatplay, @ldecoursy)

**Trainings**
- [ ] Build out NWP Training resources.
- [ ] Facilitate NWP team efforts. (cc @jvallera, @anmechung, @ldecoursy, Carolina)

**L10n**
- [x] Develop campaign 1-pager (cc @soapdog, @kevzawacki, @chrislarry33, @amirad, @ldecoursy)

**MozFest**
- [x] Send acceptance emails by 9/30/15.
- [x] Update travel requests by 9/30/15.
- [x] Iterate on "Milestone" & "Backup" sessions based on responses to acceptance emails.
- [x] Finalize Learning & Leading pathway program.
- [ ] Support remote participation work. (cc @Saallen)

**Leadership group**
- [x] Contribute to SWOT analysis, reporting, & recommendations. (cc Sam)

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by chadsansing** [comment]
Closing and moving on to [the next [Meta] issue](https://github.com/mozilla/learning-networks/issues/254).
