### ISSUE TITLE
[Meta] Curriculum work, 10/12/15 - 10/23/15

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#254]
**Meta**
- [x] Close previous tracking ticket.
- [x] Draft next tracking [Meta] issue.

**Curriculum**
- [x] Watch production on submitted modules. (cc @hannahkane)
- [ ] Integrate 21st C skills & emergent badging work w/ activities & modules. (cc @anmechung, @hannahkane)
- [x] Prototype & share 2-3 more activities for Web Literacy Basics II module. (cc @ldecoursy, @chrislarry33)
- [x] Iterate Web Literacy Basics II module materials w/ feedback from Discourse, GitHub, & testing. (cc @ldecoursy, @chrislarry33)
- [ ] Prototype another activity for the exploratory "Playground Games that Teach the Web" module. (cc @amirad)
- [ ] Blog on workflow. (@ldecoursy, @chrislarry33)
- [ ] Help prototype Web X-Ray Goggles activities. (cc @hannahkane, @flukeout)
- [x] Share curriculum rubric & contribution guidelines on Discourse for feedback (cc @ldecoursy)

**Clubs**
- [ ] Gather feedback from clubs that have tested new curriculum prototypes. (cc @amirad)

**Teach Like Mozilla**
- [ ] ~~Develop DARCI (cc @chrislarry33)~~ BLOCKED
- [ ] ~~Revisit the queue/roadmap (cc @leahatplay)~~ BLOCKED

**Trainings**
- [x] Wrap rough drafts of assigned NWP materials by 10/16/15. (cc @anmechung, @jvallera, @ldecoursy, @chrislarry33, Caro, Andrea Zellner, Christina Cantrill)
- [ ] Facilitate feedback on drafted NWP materials.
- [ ] Schedule & facilitate NWP next-steps meeting. (cc @anmechung, @jvallera, @ldecoursy, @chrislarry33, Caro, Andrea Zellner, Christina Cantrill)

**L10n**
- [ ] Champion localization campaign ahead of MozFest. 
- [x] Migrate at least two Web Literacy Basics activities into markdown. (cc @soapdog)

**MozFest**
- [x] Ask for DARCI on remaining work. (cc @LindseyFrost, Sam)
- [x] Facilitate communications re: planning. (cc @LindseyFrost, Sam)
- [x] Prototype remote participation materials. (cc @Saallen allen)

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by omnignorant** [comment]
@chadsansing @chrislarry33 I'd really like to be a part of the TLM convo and play a significant role in the DARCI. I think recent shareouts about Hive meetups, but also the RideW/Me work and other choice bits need to be captured and codified. I have thoughts and am ready to engage in that work.

**Comment by chadsansing** [comment]
Thanks, @omnignorant. Looks like we'll tackle that a bit later after strategy decisions are made. We'll loop back to it.

**Comment by chadsansing** [comment]
MozFest firehouse washed out a few items this week; will come back to them in the next several cycles.

**Comment by chadsansing** [comment]
Heading over to https://github.com/mozilla/learning-networks/issues/272.
