### ISSUE TITLE
[Meta] L10N campaign for Mozilla Clubs Activities

### ISSUE THREAD

**Issue by soapdog** [mozilla/learning-networks#271]
## Activity Template work
- [x] Add support for multiple localizations in the same repository
- [x] Switch current default locale based on browser language
- [x] Switch current default locale based on string passed on URL (enables linking to specific locale)
- [x] Create clearer instructions on how to localize activities
- [x] Create video with instructions on how to localize activities
- [x] Review instructions with peers
## L10n migration
- [x] Migrate **Kraken the Code** activity to markdown 
- [x] Migrate **Ping Kong** activity to markdown
- [x] Migrate **Hack the News** activity to markdown  
- [x] Migrate **HTML Puzzle Boxes** activity to markdown 
- [x] Migrate **Web Chef** activity to markdown 
- [x] Migrate **Story of us** activity to markdown 
- [ ] Create meta repository to point to all activity repositories for **Web Basics 1** curriculum.
### Activity repositories:
- Kraken The Code: [Source Code](https://github.com/mozilla/mozilla-club-activity-kraken-the-code) and [Live Page](http://mozilla.github.io/mozilla-club-activity-kraken-the-code/)
  - Currently available in: Indonesian, Filipino, Bengali, English, Spanish and Portuguese
- Ping Kong: [Source Code](https://github.com/mozilla/mozilla-club-activity-ping-kong) and [Live Page](http://mozilla.github.io/mozilla-club-activity-ping-kong/)
  - Currently available in: English
- Hack the News: [Source Code](https://github.com/mozilla/mozilla-club-activity-hack-the-news) and [Live Page](http://mozilla.github.io/mozilla-club-activity-hack-the-news)
  - Currently available in: Bengali, English, Portuguese
- HTML Puzzle Boxes: [Source Code](https://github.com/mozilla/mozilla-club-activity-html-puzzle-boxes) and [Live Page](http://mozilla.github.io/mozilla-club-activity-html-puzzle-boxes)
  - Currently available in: English, Bengali
- Web Chef: [Source Code](https://github.com/mozilla/mozilla-club-activity-web-chef) and [Live Page](http://mozilla.github.io/mozilla-club-activity-web-chef)
  - Currently available in: English, Portuguese, Bengali
- Story of Us: [Source Code](https://github.com/mozilla/mozilla-club-activity-story-of-us) and [Live Page](http://mozilla.github.io/mozilla-club-activity-story-of-us)
  - Currently available in: English, Bengali
## MozFest campaign work
- [x] Start localization campaign ahead of mozFest
- [ ] Work with volunteers for informal gathering during mozFest and training on how to translate activities

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by soapdog** [comment]
Moving current localized activities to github now... :smiley_cat:

**Comment by soapdog** [comment]
Migrated **Kraken the Code** to repository at: https://github.com/mozilla/mozilla-club-activity-kraken-the-code everything is correct but the github page is not loading. I suspect something wrong on their side. Checking...

**Comment by soapdog** [comment]
Github pages started behaving correctly on its on. Moving the rest of the activities.

**Comment by soapdog** [comment]
**Ping Kong** activity repo at https://github.com/mozilla/mozilla-club-activity-ping-kong

**Comment by soapdog** [comment]
Live page for **Ping Kong** http://mozilla.github.io/mozilla-club-activity-ping-kong/

**Comment by soapdog** [comment]
**Hack the News** repository: https://github.com/mozilla/mozilla-club-activity-hack-the-news

**Comment by chadsansing** [comment]
Nicely done, @soapdog!

**Comment by ldecoursy** [comment]
Thanks @soapdog Putting final touches on campaign one-pager, promise to have tomorrow.

**Comment by chrislarry33** [comment]
love it!!!!!

Chris

**Comment by ldecoursy** [comment]
One-pager is here, open for comments/suggestions: https://docs.google.com/document/d/15D57m-8dqpCvVX8e0M5oNH95ptwXgAMYXezsVkFuu7Y/edit

**Comment by chadsansing** [comment]
@soapdog, do you still need the last three activities to be written in .md? If so, assign me two of them to work on tomorrow, 10/23/15.

**Comment by soapdog** [comment]
@chadsansing thanks a lot for the help! I have them here already, just fixing them before upload. They will all be up tonight. If you could review them online tomorrow and send me feedback it will be awesome!

**Comment by chadsansing** [comment]
Yup yup.

**Comment by chrislarry33** [comment]
Read one-sheet. Looks awsm, full speed ahead. One thing is might expand it to 6 weeks, but will let you all decide.

**Comment by chadsansing** [comment]
+1 on expansion; take it to Orlando.

**Comment by soapdog** [comment]
HTML Puzzle Boxes: [Source Code](https://github.com/mozilla/mozilla-club-activity-html-puzzle-boxes) and [Live Page](http://mozilla.github.io/mozilla-club-activity-html-puzzle-boxes)

**Comment by soapdog** [comment]
+1 on expansion!!!!

**Comment by chrislarry33** [comment]
Agreement then, lets expand

**Comment by soapdog** [comment]
- Web Chef: [Source Code](https://github.com/mozilla/mozilla-club-activity-web-chef) and [Live Page](http://mozilla.github.io/mozilla-club-activity-web-chef)

**Comment by soapdog** [comment]
- Story of Us: [Source Code](https://github.com/mozilla/mozilla-club-activity-story-of-us) and [Live Page](http://mozilla.github.io/mozilla-club-activity-story-of-us)

Now, I will work on documentation to make translators/localizers life easier.

**Comment by ldecoursy** [comment]
Hi @soapdog, in the readme files, should the "easy method" be listed first? Looks like currently those instructions follow the more detailed directions for skilled GitHubbers, but I wonder if we should switch so we don't lose folks who aren't as familiar with GitHub.

**Comment by soapdog** [comment]
I am editing the instructions, should be done early tomorrow. I am adding a TOC to the Readme files and also listing the "easy method" before all the rest of the documentation.

**Comment by soapdog** [comment]
Shooting the short video for the instructions... this is a screencast demoing the _easy way_ of translating/localizing the material by pig-backing Github Issues. I would love feedback on both the instructions and video later today.

**Comment by soapdog** [comment]
@ldecoursy on the repos readme file there is now a table of contents and the easy method is listed first.

**Comment by ldecoursy** [comment]
Thanks @soapdog!

**Comment by ldecoursy** [comment]
Thanks @soapdog!

**Comment by soapdog** [comment]
@ldecoursy and @chadsansing what do you think of this quick script/outline for the video?

First of all, thanks for the interest in helping us localize our activities to other languages and contexts. This will enable us to reach a much larger audience and will unlock many opportunities for club members everywhere.

(pause)

In this short video we'll show you the quickest way to contribute with translations. To use this method you will need a working internet connection, your favorite browser, a plain text editor such as notepad or sublime text and a github account.

You can create a github account for free at github.com, you will need this account to post back your translations to us.

(pause)

In this video, we'll localize the activity called: Kraken the Code.

Once you select what activity you want to localize/translate, you need to browse its github repository and pick the two content files inside the "activity-data/content" folder. Right now, all activities have an English content, so you will go inside the "EN" folder and pick the two files called "activity.md" and "aside.md".

The aside.md file holds the content from the sidebar on the left side of the page. The activity.md file holds the content from the activity instructions.

Both files are in Markdown format and you can learn more about this format by 
going to the link below.

Open these files in your favorite text editor. Try not to use word but instead pick a plain text editor such as notepad. Edit the content paying attention to some rules explained on the link below.

Once you're done with your translation, you will post that content back to us using the issues links on the github repository for that activity. Just go to the repository, click on the issues features and add a new issues.

Remember to add a subject saying what file is being translated and what language we're using.

After you submit your new issue, someone from our team will look into it and validate. If everything is good to go, we'll update the repository and your new locale will be available.

**Comment by ldecoursy** [comment]
First of all, thanks for **your** interest in helping us localize our **Web Literacy Basics** activities to other languages and contexts. This will enable us to reach a much larger audience and will unlock many opportunities for club members everywhere.

(pause)

In this short video we'll show you the quickest way to contribute with translations. To use this method you will need a working internet connection, your favorite browser, a plain text editor such as notepad or sublime text and a github account.

You can create a github account for free at github.com, you will need this account to post back your translations to us.

(pause)

In this video, we'll localize the activity called: Kraken the Code.

**There are currently six activities we'd like to translate.** Once you select what activity you want to localize/translate, you need to browse its github repository and pick the two content files inside the "activity-data/content" folder. Right now, all activities have ~~an~~ English content, so you will go inside the "EN" folder and pick the two files called "activity.md" and "aside.md".

The aside.md file holds the content from the sidebar on the left side of the **final** page **which looks like this**. The activity.md file holds the content from the activity instructions. 

Both files are in Markdown format and you can learn more about this format by
going to the link below.

Open these files in your favorite text editor. Try not to use word but instead pick a plain text editor such as notepad. Edit the content paying attention to some rules explained on the link below.

Once you're done with your translation, you will post that content back to us using the issues links on the github repository for that activity. Just go to the repository, click on the issues features and add a new issues.

Remember to add a subject saying what file is being translated and what language **you're** using.

After you submit your new issue, someone from our team will **review it**. If everything is good to go, we'll update the repository and your new locale will be available.

[Add a closing word and thanks :)]

**Comment by soapdog** [comment]
Perfect @ldecoursy :D Thanks a lot for the fixes.

**Comment by chadsansing** [comment]
I like it. Keep it simple and conversational. +1s.

**Comment by soapdog** [comment]
@ldecoursy and @chadsansing this is the video we made https://vimeo.com/144075032 given more time we could make it better but it might be good enough for our needs. Any feedback?

**Comment by soapdog** [comment]
Adding the language information to the top as translations come in. Right now of our desired 30 translations we already have 4 which is 13%. :smile_cat:

**Comment by soapdog** [comment]
HTML Puzzle Boxes, Web Chef and Story of Us has been translated into Bengali. We're now 23% done with our translation effort. (7 out of 30)

**Comment by soapdog** [comment]
New Bengali translations: Kraken the Code, Hack the News

**Comment by chadsansing** [comment]
AWSM. Keep it up, l10n community! Thank you!

**Comment by chadsansing** [comment]
@soapdog, where are we percentage wise? What current needs stand out right now?

**Comment by soapdog** [comment]
@chadsansing we have 30% now! :smile_cat: The translations that are most complete are the Bengali and Portuguese ones. In third place we have the Spanish. Since our target included more languages besides those three then we may need to reach out to Reps from those specific regions.

**Comment by soapdog** [comment]
**Kraken the Code**: has been translated into Indonesian and Filipino.

Both **Hack the News** and **HTML Puzzle Boxes** received corrections to their Bengali translations

**Comment by soapdog** [comment]
@chadsansing we're now 40% done :joy_cat: soon we'll have 50% and be able to do something like a second blog post inviting more contributions.

**Comment by hannahkane** [comment]
@soapdog / @ldecoursy - Should we change the links from https://teach.mozilla.org/activities/web-lit-basics/ to refer to these new pages? 

Also, @soapdog, is there any way to link directly to translations, or do we have to link to the master page, and include instructions for how to change the language once on the page?

**Comment by ldecoursy** [comment]
Yes - although we might want to wait until we have all six activities translated - currently we have all six in Bengali, half in Portuguese, and a few activities in Spanish, Indonesian and Filipino...

**Comment by hannahkane** [comment]
OK, will wait until all of the translations are in. Thanks!

**Comment by soapdog** [comment]
@hannahkane yes, you can link directly to a translation by using the hash part of an url such as:
- Indonesian: http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#id
- Portuguese: http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#pt
- Bengali: http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#bn

:smile_cat:

**Comment by hannahkane** [comment]
w00t. Thanks, @soapdog!

**Comment by ldecoursy** [comment]
@soapdog, @kgorr is going to draft an interim blog post for next week with an update on where we are, and what we still need - she'll reach out for more details. :)

**Comment by ldecoursy** [comment]
@soapdog OK to close?

**Comment by soapdog** [comment]
OK to close!
