### ISSUE TITLE
[Meta] Curriculum Work, 10/16/15 - 11/06/15

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#272]
**Meta**
- [x] Close previous tracking ticket.
- [x] Draft next tracking [Meta] issue.

**Curriculum**
- [x] Watch production on submitted modules. (cc @hannahkane)
- [ ] Integrate 21st C skills & emergent badging work w/ activities & modules. (cc @anmechung, @hannahkane)
- [x] Iterate Web Literacy Basics II module & draft a content doc (cc @ldecoursy, @chrislarry33, @hannahkane)
- [ ] Blog on MozFest. (@ldecoursy, @chrislarry33)

**Clubs**
- [ ] Gather feedback from clubs that have tested new curriculum prototypes. (cc @amirad)

**Teach Like Mozilla**
- [x] Watch Phase 3 planning for TLM opps.

**Trainings**
- [x] Facilitate feedback on drafted NWP materials.
- [x] Convene next-steps meeting. (cc @anmechung, @jvallera, @ldecoursy, @chrislarry33, @carot, Andrea Zellner, Christina Cantrill)

**L10n**
- [x] Champion localization campaign ahead of MozFest. (cc @soapdog, @KevZawacki, @kgorr, @ldecoursy, @chrislarry33)

**MozFest**
- [x] Wrangle wrangle. Pathfind. Wrangle. Wrangle pathfind pathfind. Wrangle.
- [x] Complete remote facilitation hand-off. (cc @Saallen , @fuzzyfox)
- [x] Finish facilitator 1:1 meetings. (cc @LindseyFrost, @saallen)
- [x] Finish program copy.
- [x] Finish scheduling.
- [x] Get to London.
- [x] Facilitate like a boss. 

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by chadsansing** [comment]
Arriving from https://github.com/mozilla/learning-networks/issues/254.

**Comment by chadsansing** [comment]
On to [#280](https://github.com/mozilla/learning-networks/issues/280).
