### ISSUE TITLE
[MozFest Club Guides] Participatory & Playful learning in Mozilla Clubs

### ISSUE THREAD

**Issue by soapdog** [mozilla/learning-networks#273]
# Description

This is the organizational plan for the creation of a new guide for the Mozilla Clubs based on the outcomes of the MozFest session (https://github.com/mozilla/mozfest-program/issues/274) of the same name being facilitated by Shreyas Kutty.
# Plan

The session will be a fireside chat where we'll share experiences, collect and document teach practices from all over the world. We want to collect in a single place the cream of these teaching experiences discovering what works and what doesn't work in the different countries and regions. We envision this being an ongoing process that will keep happening after MozFest as well.

The way Shreyas structured his session already leads to data collection and the objective was always to create something shareable. This already fits well with our guides masterplan and all we need is to make sure the content is collected well.
# ToDos
- [x] Chat with Shreyas about the session and the creation of the guide
- [ ] Create repository for the guide with boilerplate
- [ ] Create little document on the wiki about how to collect data

**Comment by soapdog** [comment]
cc @dunebuggie

**Comment by soapdog** [comment]
This may overlap a bit with #275. If this is the case we'll merge them both into a final guide about participatory and collaborative methods.

**Comment by Carotejada** [comment]
#281 here we have merged guides and documentation / Mozfest_2105

**Comment by amirad** [comment]
Done! https://docs.google.com/document/d/1lKjPm-k3GGtz66Lor_kRpX68HNaPj-T47tmZ540WY_w/edit
