### ISSUE TITLE
[MozFest Club Guides]  From Participation to Collaboration

### ISSUE THREAD

**Issue by soapdog** [mozilla/learning-networks#275]
# Description

This is the organizational plan for the creation of a new guide for the Mozilla Clubs based on the outcomes of the MozFest session (https://github.com/mozilla/mozfest-program/issues/513) of the same name being facilitated by Hélène Petry
# Plan

The session will be a [World Café](http://www.theworldcafe.com/key-concepts-resources/world-cafe-method/). This method uses small groups and rotating people to explore different questions and generate answers and better questions. One person is tasked with keeping the memory of each group and we'll help these people collect the data we need for the guide.

This guide will probably overlap a bit with #273 and if we identify that their scopes are too similar we may merge them. While #273 explores what is working inside Mozilla Clubs, this one explores participation and collaboration in general and may serve to generate new leads for activities and methods.
# ToDos
- [x] Chat with Hélène about the session and the creation of the guide
- [ ] Create repository for the guide with boilerplate
- [ ] Create little document on the wiki about how to collect data

**Comment by amirad** [comment]
Done! https://docs.google.com/document/d/158EUUSBRz8klFl-gZQ1Cgs3ZtgZWErSw7Pqe3fhcDnY/edit
