### ISSUE TITLE
[MozFest Club Guides]  Using Digital Fabrication Techniques to Make DIY Activist Gear

### ISSUE THREAD

**Issue by soapdog** [mozilla/learning-networks#279]
# Description

This is the organizational plan for the creation of a new guide for the Mozilla Clubs based on the outcomes of the MozFest session (https://github.com/mozilla/mozfest-program/issues/520) of the same name being facilitated by Drew Wilson.
# Plan

The session is divided in two parts. The first one is an exposition about the different tools and techniques available and how to apply them. The second part is the practical one where we use stencils and potentially other stuff to print banners, t-shirts and bags.

I believe that the most interesting item for this guide is the first part of the session which would be great in a cookbook sort of guide explaining techniques, tools and how to apply them in club context. We could at a later date collect successful stories of clubs applying those techniques for a case study section at the guide. So the tentative high-level birds-eye-view of the guide would be one section explaining techniques and tools, one section explaining how they apply for clubs and a final section on case studies from other clubs.
# ToDos
- [x] Chat with Drew about the session and the creation of the guide
- [ ] Create repository for the guide with boilerplate
- [ ] Create little document on the wiki about how to collect data

**Comment by amirad** [comment]
We opted not to do this with Drew since he had many post already on this topic.
