### ISSUE TITLE
[Meta] Curriculum work, 11/9/15 - 11/20/15

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#280]
**Meta**
- [x] Close previous tracking ticket.
- [x] Draft next tracking [Meta] issue.

**Curriculum**
- [x] Blog on MozFest. (@ldecoursy, @chrislarry33)
- [x] Start a new curriculum template print-CSS discussion. (@hannahkane)
- [x] Schedule an MLN Curriculum Plan meeting to begin scoping cross-over and collaborative opportunities to work on curriculum 'best' or common practices throughout Mozilla.

**Clubs**
- [ ] Debrief from MozFest & Test @ the Fest testing. (cc @hannahkane, @amirad)
- [x] Planning meeting w/ BETA Academy teachers re: test-kitchen club. (@ldecoursy, @chrislarry33, @amirad)

**Trainings**
- [x] Migrate finished materials from NWP folder to Thimble. (cc @jvallera, @anmechung, @ldecoursy, @carot, Andrea, Christina
- [x] Check-in meeting.
- [x] Schedule a logistics meeting or meal.
- [x] Get to Minneapolis.
- [x] Workshop w/ Afterschool Alliance.
- [x] Workshop w/ NWP teachers.
- [ ] ~~TTT onsite.~~
- [x] Review NYCDOE Stem framework and ship @ldecoursy connections to IPPD workshop.

**L10n**
- [x] Tweet in support of campaign. (cc @soapdog, @KGorr, @KevZawacki, @ldecoursy, @chrislarry33)

**MozFest**
- [x] Facilitate the facilitators' work.
- [x] Thank facilitators.
- [x] Debrief w/ team.
- [x] Follow up re: MDN Web Security modules.
- [x] Follow up re: interactive explainers.
- [x] Follow up re: Para Para 3D module.
- [x] Follow up re: game-informed curriculum.
- [x] Follow up re: Songhay curriculum localization.
- [x] Follow up re: Scratch.

[Back to isses.](https://github.com/mozilla/learning-networks/issues)

**Comment by chadsansing** [comment]
Arriving from [#272](https://github.com/mozilla/learning-networks/issues/272).

**Comment by chadsansing** [comment]
Based on MozFest follow-up with Kudo & Mozilla Factory, I'm planning to update the [Para Para Kit](https://karenlouisesmith.makes.org/thimble/para-para-animation-teaching-kit).
- [x] Migrate [landing page](https://karenlouisesmith.makes.org/thimble/para-para-animation-teaching-kit) and [existing activity](https://karenlouisesmith.makes.org/thimble/LTEyMjYxNzg1Ng==/para-para-activity) to updated templates.
- [x] Link to [Fabble projection-mapping activity](http://fabble.cc/comozilla/pm-with-parapara).
- [x] Link to [Fabble tutorial for documenting your own projects](http://fabble.cc/fabble/tutorial-en).

cc @ldecoursy, @hannahkane, @chrislarry33, @smithisgeneric

**Comment by chadsansing** [comment]
See http://chadsansing.github.io/curriculum-testing/para-para-and-fabble/index.html.

**Comment by chadsansing** [comment]
Heading to [#283](https://github.com/mozilla/learning-networks/issues/283).
