### ISSUE TITLE
[Meta] Curriculum work, 11/23/15 - 12/4/15

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#283]
**Meta**
- [x] Close previous tracking ticket.
- [x] Draft next tracking [Meta] issue.

**Curriculum**
- [x] Convene cross-Mozilla curriculum plan call. (cc @chrislarry33, @carot, @zeemoz, @amirad, @hannahkane, George Roter, Emma Irwin, Chris Mills, Jeremie Patonnier)
- [x] Chattanooga digital literacy chat.
- [x] Royal Foundation conservation curriculum chat.
- [x] MoCo privacy curriculum support chat. (cc @chrislarry33)
- [x] Follow-up on NWP Letters to the Next President partnership. (cc @ldecoursy, @chrislarry33)
- [x] Draft interactive design and development workplan. (cc @chrislarry33)
- [ ] Soft-launch Web Lit Basics II for testing ahead of Q1 2016 migration to new template. (cc @hannahkane, @ldecoursy, @chrislarry33)
- [x] Begin scoping activities and modules for Q1 2016. (cc @ldecoursy, @chrislarry33, @amirad)

**Clubs**
- [x] Plan test-kitchen club info meeting for BETA students. (cc @amirad, @carot, @soapdog)

**Trainings**
- [x] Report on NWP feedback. (cc @ldcoursy, @chrislarry33, @anmechung, @jvallera, @carot)
- [ ] ~~IPPD check-in meeting. (cc @ldecoursy, @jvallera, @carot, @anmechung)~~

**L10n**
- [x] Monitor progress. (cc @ldcoursy, @soapdog)
- [x] Tweet in support of the campaign.

**Orlando**
- [x] Prep.

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by chadsansing** [comment]
Arriving from [#280](https://github.com/mozilla/learning-networks/issues/280).

**Comment by chadsansing** [comment]
Headed over to [#284](https://github.com/mozilla/learning-networks/issues/284).
