### ISSUE TITLE
[Meta] Curriculum work, 12/7/15 - 12/18/15

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#284]
**Meta**
- [x] Close previous tracking ticket.
- [ ] Draft next tracking [Meta] issue.

**Orlando**
- [x] Participate in curriculum & design meeting.
- [x] Facilitate Mozilla Curriculum Plan meeting.
- [x] Participate in Fabble meeting.
- [x] Promote innovative curriculum work.
- [x] Suggest specific development, testing, and roll-out windows and dates for curriculum work.
- [x] Grok web lit positioning w/in Advocacy and Leadership engines.
- [x] Plug into H1, Q1 work on leadership curriculum, clubs curriculum, advocacy curriculum.
- [x] Prep work team preso/product to share Friday.

**Orlando Follow-up**
- [x] Send Clubs materials to Kudo.
- [x] Send Clubs materials to Su.
- [x] Send clubs materials to Sarah.
- [x] Summarize Fabble meetings notes and next steps: replace maker examples in curriculum with Fabble recipes, connect Fabble to MoFo documentation opportunities, connect Fabble to MozFest documentation opportunities, connect Fabble to Moz Clubs event reporting opportunities, continue Mozilla Japan and MoFo research conversation, continue Mozilla Japan and MoFo IOT conversation.
- [x] Email summary to Fabble meeting attendees and facilitate follow-up conversations.
- [x] Continue Web Lit assessment conversation with An-Me and Clubs.
- [x] Summarize Mozilla Curriculum Plan Meeting and schedule small-group follow-ups in early Q1 2016.
- [ ] Schedule next whole-group Mozilla Curriculum Plan call before the end of January 2016.
- [ ] Track long-term opportunities for collaboration w/ MoCo & MoFo community members interested in interactive & games-based curriculum development.

**Curriculum**
- [x] Soft-launch Web Lit Basics II for testing ahead of Q1 2016 migration to new template. (cc @hannahkane, @amirad, @omnignorant, @animaltinez, @ldecoursy, @chrislarry33, @soapdog, @leahatplay, @anmechung, @carot)
- [ ] Launch updated Parapara module with 3d projection-mapping and Fabble materials. (cc @hannahkane)
- [x] Finish prototyping intermediate web literacy CSS activities; move from 3 to 6+.
- [x] Set up Discourse threads for Web Lit Basics II and CSS curriculum testing.
- [ ] Begin templating event reports and case studies reverse-engineered from @carot's work. (cc @carot, @zeemoz)
- [ ] Help MoCo Privacy migrate curriculum to Thimble and develop encryption curriculum. (cc @chrislarry33)
- [x] Draft copy for Spark Hackathon 'Fight for the Open Web in Minecraft' session. Share to Sarah and Robert.
- [x] Start a Web Lit Map 2.0 crosswalk document to Web Lit Basics I & II activities. (cc @anmechung)

**Clubs**
- [x] Run test kitchen club information session for intwerested teachers and students. (cc @amirad, @carot, @sopadog)

**Hive**
- [ ] Develop narrative around [#weartherangers brokering](http://wearetherangers.com/wildlife-in-crisis/). (cc @jvallera, @ldecoursy, @chrislarry33)

**Trainings**
- [x] Iterate curriculum towards IPPD training. (cc @ldecoursy, @anmechung, @carot, @jvallera, @chrislarry33)
- [ ] Iterate curriculum toward Beyond School Hours training.
- [ ] Iterate curriculum towards National Afterschool Alliance training.

**L10n**
- [x] [Monitor progress](https://d157rqmxrxj6ey.cloudfront.net/andregarzia/17163/). (cc @ldecoursy, @soapdog)
- [x] Tweet in support of the campaign.

**NWP**
- [ ] Prototype activities and/or templates for NWP Letters to the Next President partnership. (cc @ldecoursy, @chrislarry33)

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by chadsansing** [comment]
Arriving from [#283](https://github.com/mozilla/learning-networks/issues/283).

**Comment by chadsansing** [comment]
Next [meta] in 2016.

**Comment by chadsansing** [comment]
Headed to [#294](https://github.com/mozilla/learning-networks/issues/294).
