### ISSUE TITLE
[Meta] Curriculum work, 1/4/16 - 1/15/16

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#294]
**Meta**
- [x] Close previous tracking ticket.
- [ ] Draft next tracking ticket.

**Web Literacy Curriculum**
- [ ] Revise Basic Web Literacy II &amp; Intermediate Web Literacy: CSS I modules.
- [ ] Migrate new modules into new template as able.
- [ ] Follow-up on updated Parapara module with 3d projection-mapping &amp; Fabble materials. (cc @hannahkane)
- [x] Prototype bridge &amp;/or extension activities (e.g. movie poster) Intermediate Web Literacy: CSS I module.
- [ ] Create a content document for Intermediate Web Literacy: CSS I module. (cc @ldecoursy, @chrislarry33, @hannahkane)
- [ ] Prototype new Web X-Ray Goggles activities.
- [ ] Prototype new A-Frame activities.
- [ ] Scope Intermediate Web Literacy: CSS II module.
- [ ] Scope Intermediate Web Literacy: JavaScript I module.

**Leadership Curriculum**
- [ ] Facilitate Mozilla Curriculum Team working group meetings to work on topics &amp; towards deliverables from Orlando meeting. 
- [x] Schedule meetings before January 22nd for _contribution & participation in curriculum development_, _reviewing MDN content for inclusion in MoFo curriculum_, &amp; _ask club captains to share best practices_ working groups.
- [ ] Facilitate those meetings.
- [x] Schedule whole-group meetings for January &amp; February.
- [ ] Facilitate those meetings. (@chrislarry33)
- [x] Set-up &amp; maintain [shared doc for notes](https://docs.google.com/document/d/17AWV0Yv1Ojuu4Vc4qYmUhIDE7Ud8wUSRH8eKmiFMLQk/edit#heading=h.l6u7nzcwrbl4).
- [x] Draft &amp; vet H1 leadership curriculum authoring plan.
- [ ] ~~Share the plan for feedback.~~
- [ ] ~~Share the plan w/ Mozilla Curriculum Team for discussion &amp; action.~~
- [x] Share the premise of the plan for feedback from the Curriculum Team. 

**Clubs**
- [x] Check-in with @Carotejada re: documentation &amp; reporting templates.
- [ ] Plan local session for 1/25/18.

**Spark Hackathon**
- [x] Draft problem statement for review. (cc @ldecoursy)
- [x] Ship problem statement to Kim Wilkens.
- [ ] Begin planning web literacy workshop for 1/30/16.

**IPPD**
- [x] Build [IPPD workshop site](https://d157rqmxrxj6ey.cloudfront.net/chadsansing/22146/) in Thimble. (cc @ldecoursy, @anmechung, @jvallera, @carot)
- [ ] Revise content for NYC DOE IPPD audience.
- [x] Create privacy &amp; security game &amp; discussion prompts.
- [ ] Facilitate spectrogram &amp; OER revisions.

**L10n**
- [ ] ~~Follow the campaign](https://d157rqmxrxj6ey.cloudfront.net/andregarzia/17163/). (cc @ldecoursy, @soapdog)~~
- [x] Debrief on the campaign.

**NWP**
- [x] Attend NWP New Pathways retreat from 1/10/16 to 1/14/16 (cc @ldecoursy, @chrislarry33)
- [ ] Prototype activities &amp;/or templates for NWP Letters to the Next President partnership.

**Community**
- [ ] Prep for start of curriculum design workshop hangouts.

Arriving from [#284](https://github.com/mozilla/learning-networks/issues/284).

[Back to issues.](https://github.com/mozilla/learning-networks/issues/)

**Comment by anmechung** [comment]
Looks great, and looking forward to participating!

**Comment by chadsansing** [comment]
+1, @anmechung.

**Comment by chadsansing** [comment]
Also learned some Sass/scss. Good times.

**Comment by chadsansing** [comment]
Headed to [#309](https://github.com/mozilla/learning-networks/issues/309)
