### ISSUE TITLE
[Meta] Curriculum work, 1/18/16 - 1/29/16

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#309]
**Meta**
- [x] Close previous tracking ticket.
- [ ] Draft next tracking [Meta] issue.

**Web Literacy Curriculum**
- [x] Revise Basic Web Literacy II &amp; Intermediate Web Literacy: CSS I modules.
- [x] Test activities from the new module in the new curriculum template.
- [x] Follow-up on updated Parapara module with 3d projection-mapping &amp; Fabble materials.
- [x] Create a content document for Intermediate Web Literacy: CSS I module.
- [ ] ~~Prototype new Web X-Ray Goggles activities.~~
- [ ] ~~Prototype new A-Frame activities.~~
- [ ] ~~Scope Intermediate Web Literacy: CSS II module.~~
- [ ] ~~Scope Intermediate Webv Literacy: JavaScript I module.~~

**Leadership Curriculum**
- [x] Facilitate Mozilla Curriculum Team working group meetings.
- [x] Facilitate working group projects.
- [x] Facilitate January whole-group Curriculum team meeting.
- [x] Crosswalk Participation Leadership Framework v0.1 and MoFo Information Architecture for Leadership designs. (@chrislarry33)

**Clubs**
- [ ] ~~Plan local session for 1/25/18.~~
- [ ] Iterate on event reporter.

**Spark Hackathon**
- [x] Finish planning for web literacy workshop on 1/30/16.
- [x] Build workshop as a Thimble project.

**IPPD**
- [x] Revise content for NYC DOE IPPD audience.
- [ ] ~~Facilitate spectrogram &amp; OER revisions.~~
- [x] Build out issues.
- [ ] Track [issues](https://github.com/mozilla/learning-networks/issues/313).

**NWP**
- [x] Prototype activities &amp;/or templates for NWP Letters to the Next President partnership.

**Community**
- [x] Spin-up curriculum workshop hangout.

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by chadsansing** [comment]
Arriving from [#294](https://github.com/mozilla/learning-networks/issues/294).

**Comment by chadsansing** [comment]
Other things going on: migrating curriculum, setting up a community curriculum workshop hangout, working on interactive media w/ Luke & Matthew, participating in/wrangling Mozilla Curriculum Team calls & Fabble call with Mozilla Japan. Thinking about encryption teaching resources. Thinking about curriculum and Thimble marketing. Etc.

**Comment by hannahkane** [comment]
Curious about the interactive media. Can you say more about it?

**Comment by chadsansing** [comment]
@hannahkane - [check it](https://drive.google.com/a/mozilla.com/folderview?id=0B0RBD2BW-srIS0h2T1VYN1RjczQ&usp=sharing).

**Comment by chadsansing** [comment]
[SPARK agenda](https://d157rqmxrxj6ey.cloudfront.net/chadsansing/28805/index.html).

**Comment by chadsansing** [comment]
Going to [#329](https://github.com/mozilla/learning-networks/issues/329).
