### ISSUE TITLE
[Meta] Spring 2016 IPPD Mozilla Web Literacy Leaders Workshop

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#313]
**Goals:**

Deliver a web literacy leadership workshop for formal and informal NYC-area educators that leads to:
- At lest X% of participants using web literacy practices between February and April, 2016.
- At least X% positive feedback from participants.

**Overview**

From [our program description](https://docs.google.com/document/d/1p-xFf0dNiNaenQabdkLjWSEqIpRrgMQ12ASfutrZt7I/edit#):

_This program is designed for middle and high school educators who want to infuse the web into their teaching, across any subject area. Participants will have the opportunity to practice and learn web literacy skills, including web mechanics, composing (basic coding via HTML and CSS), remixing, privacy, community participation, open practices, and sharing. Activities also align to 21st Century Skills for collaboration, communication, creativity, and problem-solving._

_During the Mozilla Web Literacy Leaders program, participants will receive hands-on experience with Web X-Ray Goggles and Thimble code editor–both are free and accessible online tools that make making and learning on the Web engaging, participatory and fun. The activities we’ll focus on throughout the workshop have been created by educators and technologists, and tested in schools, after-school programs, libraries, and community centers around the globe._

_Following this workshop, participants will feel confident and empowered to create (or remix) online activities that they can teach to their students._

_No previous coding experience is required._

**Key dates**
- **Applications received:** February 3rd, 2016
- **Send notifications to accepted participants:** February 5th, 2016 
- **Materials deadline:** February 5th, 2016
- **Prep deadline:** February ~~19th~~ 20th, 2016 
- **Workshop:** February 24th, 2016
- **Closing celebration:** April 20th, 2016

**DARCI**

**Decision Maker:** Lainie
**Accountable:** Chad
**Responsible:** An-Me, Caro, Joey, Julia
**Consulted:** Lisa Nielsen (NYC DOE)
**Informed:** CLaw, Zannah, MLN

**To-do**
- [x] [Update privacy game scoresheet](https://github.com/mozilla/learning-networks/issues/314) (@chadsansing)
- [x] [Update copy](https://github.com/mozilla/learning-networks/issues/315) (@anmechung, @chadsansing)
- [x] [Update OER copy](https://github.com/mozilla/learning-networks/issues/316) (@anmechung)
- [x] [Develop post-workshop survey](https://github.com/mozilla/learning-networks/issues/317) (@anmechung)
- [x] [Finalize Thimble workshop curriculum](https://github.com/mozilla/learning-networks/issues/318) (@chadsansing)
- [x] Send link to signup via FB and Twitter (Joey)
- [x] Review applications during ~~2/2/16~~ 2/4/16 meeting (all)
- [x] [Breakfast & lunch](https://github.com/mozilla/learning-networks/issues/319) (@jvallera, Joey)
- [x] [Finalize space logistics](https://github.com/mozilla/learning-networks/issues/320) (Ariam & Joey)
- [x] [Print agenda with bit.ly links to Thimble workshop, privacy game scoresheet, and post-workshop survey](https://github.com/mozilla/learning-networks/issues/321) (@jvallera)
- [x] [Print scoresheets for the privacy game](https://github.com/mozilla/learning-networks/issues/321) (@jvallera)
- [x] [Print Tag-Tag-Revolution cards](https://github.com/mozilla/learning-networks/issues/322) (@jvallera)
- [x] [Bring computers](https://github.com/mozilla/learning-networks/issues/323) (@caro & @jvallera)
- [x] [Bring supplies](https://github.com/mozilla/learning-networks/issues/323) (@caro & @jvallera)
- [x] [Develop follow-up activities and CTAs for participants' use on Discourse](https://github.com/mozilla/learning-networks/issues/324) (@anmechung & @jvallera).
- [x] Draft acceptance/rejection letters (@ldecoursy).
- [x] Create mechanism to confirm participants (@carotejada)
- [x] Prepare and send [acceptance/rejection materials](https://github.com/mozilla/learning-networks/issues/326) (@carotejada).
- [ ] Post Discourse prompts and facilitate other comms between the workshop and celebration. (@ldecoursy)

cc @chrislarry33 

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by chadsansing** [comment]
@ldecoursy, @jvallera, @anmechung, @Carotejada - anything we can check off here/close before today's meeting?

**Comment by jvallera** [comment]
Adding @jazoulai for some of the logistical stuff. An Me and I started #324 and #317 but not ready to close yet.

**Comment by chadsansing** [comment]
Update re: final materials - we've moved on to  https://d157rqmxrxj6ey.cloudfront.net/chadsansing/31650/ for the site.

**Comment by anmechung** [comment]
@chadsansing can you change 2:15 - 3 pm to just Reflections and Next Steps?  https://d157rqmxrxj6ey.cloudfront.net/chadsansing/31650/

**Comment by chadsansing** [comment]
@anmechung, done.

**Comment by chadsansing** [comment]
Go, team, go!

**Comment by ldecoursy** [comment]
@chadsansing Can we close this ticket? Maybe will add more following our check-in call next week (planning for sustained engagement leading up to celebration, and planning for celebration itself).

**Comment by chadsansing** [comment]
@ldecoursy - so long as office hours, prompts, and celebration logistics are live, we ought to track them somewhere. New issue?

**Comment by ldecoursy** [comment]
Yes, let's plan new tickets as part of our call on Tuesday then.

**Comment by chadsansing** [comment]
Yes + close then.
