### ISSUE TITLE
[Meta] Curriculum Work, 2/1/16 - 2/12/16

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#329]
**Meta**
- [x] Close previous tracking ticket.
- [x] Draft next tracking [Meta] issue.

**Web Literacy Curriculum**
- [x] Talk with @hannahkane and @ldecoursy about transitioning Web Lit Basics II to pages migrated to the new template.
- [x] Ship Intermediate Web Lit I: Intro to CSS content doc to @hannahkane.
- [x] Consult on teaching materials for encryption campaign.
- [x] Draft encryption key lesson plan for the encryption campaign.
- [ ] Draft the  telephone game lesson plan for the encryption campaign.
- [x] Work on Teaching Coding article for SLJ.
- [x] Work on post re: VR pedagogy for Gigabit RFP.

**Leadership Curriculum**
- [x] Collate whole-group feedback on leadership curriculum framework and timeline.
- [x] Check-in with @chrislarry33 re: framework language.
- [x] Invite volunteer co-authors to determine structure and begin work curating and creating chapters/modules.

**Clubs**
- [x] Plan local session for 2/9/16.

**IPPD**
- [ ] Wrangle [tickets](https://github.com/mozilla/learning-networks/issues/313).
- [x] Review applications.

**NWP**
- [x] Prototype candidate quote poster in Thimble.
- [x] Prototype candidate meme in Thimble.
- [x] Prototype campaign poster in Thimble.
- [x] Add 2-3 letter templates to Thimble.
- [ ] Get more context copy (e.g. how are letters shared?) from NWP. (cc @ldecorusy)
- [x] Collaborate with Jeremy from [Hypothes.is](http://hypothes.is) on an annotation and Web X-Ray Goggles activity.
- [x] Share digital writing badge work with New Pathways working group.

**Community**
- [x] Work with @kgorr on improving curriculum visibility.
- [ ] Plan first workshop curriculum episode with @amirad and @ohnopauloh.
- [ ] Send invites for first episode.
- [x] File design brief.
- [ ] Work with @hannahkane et al. on landing page.
- [x] Find a producer.

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by chadsansing** [comment]
Arriving from [#309](https://github.com/mozilla/learning-networks/issues/309).

**Comment by jgmac1106** [comment]
In Terms of hypothes.is I have these activities already built which use open annotation and x-ray goggles to hack the credibility of websites:

http://networkedlearningcollaborative.com/the-courses/question-the-web/professional-development/annotate-the-web/

http://networkedlearningcollaborative.com/the-courses/question-the-web/professional-development/remix-credibility/

We could do something similar. If Hypothes.is and NWP were interested I would love to blow this up into an Open research project on teaching website credibility.

**Comment by chadsansing** [comment]
Very cool. Will reference in whatever election-flavored resource we devise, and will share that here for input. [New Goggles is live](https://goggles.mozilla.org), so I imagine we'll need an updated 'Hack the News' activity soon.

**Comment by jgmac1106** [comment]
oohh okay this is pat of #nextprez didn't realize it went that way.
Remixing candidates platforms is always a fun x-ray goggles activity.

**Comment by chadsansing** [comment]
Also to do: more unpacking Minecraft at SPARK and TTT.

**Comment by chadsansing** [comment]
Headed over to [#341](https://github.com/mozilla/learning-networks/issues/341).
