### ISSUE TITLE
[Meta] Curriculum work, 2/15/16 - 2/26/16

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#341]
**Meta**
- [x] Close previous tracking ticket.
- [x] Draft next tracking [Meta] issue.

**Web Literacy Curriculum**
- [x] Work with @mmmavis  and @hannahkane to learn how to update /activities.
- [ ] Ship Intermediate Web Literacy I: Intro to CSS
- [ ] Update Web Literacy Basics II links.
- [x] Draft a texonomy for feedback.
- [x] Draft encryption Telephone-Werewolf Game.
- [x] Write-up Minecraft/"Fight for the Open Web" recommendations.

**Leadership Curriculum**
- [x] Facilitate whole-group February call.
- [x] Scope contents.
- [x] Determine structure.
- [x] Begin drafting.

**Clubs**
- [x] Plan local session for 2/22/16.

**IPPD**
- [x] Wrangle [tickets](https://github.com/mozilla/learning-networks/issues/313).
- [x] Get to NYC.
- [x] Help facilitate IPPD training.

**NWP**
- [x] Continue contributing to New Pathways work.
- [ ] Schedule webcast with Hypothes.is

**Community**
- [x] Send invites for first curriculum workshop episode.
- [x] Confirm invites.
- [x] Work with design and development on landing page, slides/tiles.

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by chadsansing** [comment]
Arriving from [#329](https://github.com/mozilla/learning-networks/issues/329).

**Comment by chadsansing** [comment]
Heading to [#351](https://github.com/mozilla/learning-networks/issues/351).
