### ISSUE TITLE
[Meta] Curriculum Work, 2/29/16 - 3/11/16

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#351]
**Meta**
- [x] Close previous tracking ticket.
- [x] Draft next tracking [Meta] issue.

**Web Literacy Curriculum**
- [x] Ship Intermediate Web Literacy I: Intro to CSS.
- [ ] ~~Gigabit office hours.~~

**Leadership Curriculum**
- [x] Review scope and sequencing with @zee-moz.
- [x] Review alpha materials.
- [ ] Reach consensus on structure.
- [ ] Continue drafting.

**Kenya DSO**
- [x] Brainstorm curriculum ideas.
- [x] Share ideas with community for feedback..
- [ ] Consult on lesson plan production with DSO community.

**Clubs**
- [x] Plan local session for 3/14/16.

**IPPD**
- [x] Follow-up on Discourse responses for week 1.
- [x] Participate on the first office hours call.

**NWP**
- [x] Schedule webcast with Hypothes.is - maybe as May Curriculum Workshop episode.
- [x] Help plan NWP Spring Meeting roundtable with @ldecoursy and Iris.
- [x] Attend online #newpathways badges meeting.

**Community**
- [x] Check in w/ team re: first curriculum workshop webcast.
- [x] Co-host webcast.
- [ ] Debrief.
- [x] Blog.

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by chadsansing** [comment]
Arriving from [#341](https://github.com/mozilla/learning-networks/issues/341).

**Comment by chadsansing** [comment]
Heading to [#362](https://github.com/mozilla/learning-networks/issues/362).
