### ISSUE TITLE
[Meta] Curriculum Work, 3/14/16 - 3/25/16

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#362]
**Meta**
- [x] Close previous tracking ticket.
- [ ] Draft next tracking [Meta] issue.

**Web Literacy Curriculum**
- [x] Follow up on Web Lit Basics II migration update.
- [x] Follow up on Intermediate Web Lit I: Intro to CSS.
- [x] Scope, sequence, and prototype some Intermediate Web Lit II: Storytelling with Scripts (a.k.a. Intro to JS) lessons.

**Leadership Curriculum**
- [x] Draft content w/ @zee-moz.
- [ ] Blocked. ~~File interactive media design requests.~~
- [ ] Blocked. ~~Determine format for staffer and community stories.~~
- [ ] Blocked. ~~Sent invites and requests for staffer and community stories.~~

**Kenya DSO**
- [x] Work with curriculum development team on Intervention 1.

**Clubs**
- [ ] ~~Facilitate local session on 3/15/16.~~

**IPPD**
- [x] Follow-up on Discourse prompts.

**NWP**
- [x] Follow up on New Pathways and Web Lit Map 2.0 round-tables at NWP Spring Meeting.
- [x] Hold online #2NextPrez office hours.

**Trainings**
- [x] Finalize abbreviated workshop agenda with @anmechung.
- [x] Get to Orlando.
- [x] Faciliate afterschool conference web lit workshop.

**Community**

[April 12 MCW tracking issue](https://github.com/mozilla/learning-networks/issues/368).
- [x] Facilitate March 8th episode debrief w/ @amirad, @poh, @chrislarry33, @kgorr, @ldecoursy.
- [x] Plan April 12th physical computing ~~IoT~~ episode with @amirad and @poh.
- [x] Send invites for April 12th physical computing ~~IoT~~ episode.
- [x] Confirm guests for April 12th physical computing ~~IoT~~ episode.
- [x] Send guest surveys for April 12th physical computing ~~IoT~~ episode.
- [ ] File issues for design and development requests (e.g. credit tiles, music).

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by chadsansing** [comment]
Arriving from [#351](https://github.com/mozilla/learning-networks/issues/351).

**Comment by chadsansing** [comment]
On PTO next week; new meta issue tracking curriculum work ships on 4/4/16.

**Comment by chadsansing** [comment]
Waiting on graphics & music requests pending word from education participation repo community.

**Comment by chadsansing** [comment]
Heading to [#376](https://github.com/mozilla/learning-networks/issues/376).
