### ISSUE TITLE
[Meta] Curriculum work, 4/4/16 - 4/15/16

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#376]
**Meta**
- [x] Close previous tracking ticket.
- [x] Draft next tracking [Meta] issue.

**Web Literacy Curriculum**
- [x] Finish lesson plans for intermediate-web-lit-two project.
- [x] Migrate intermediate-web-lit-two projects to Thimble.
- [x] Begin writing tutorials for intermediate-web-lit-two projects in Thimble.

**Leadership Curriculum**
- [x] Meet with feedback group.
- [x] Revise open leadership, working open, and convening, facilitating, and organizing modules.
- [ ] ~~Draft GH module~~.
- [x] Prep [modules](https://docs.google.com/document/d/1ovVVKv_TlMxIWkEoHbboXvxq4UYHbmYFX3xtgQ40IJQ/edit#) for DC work sprint.

**Kenya DSO**
- [x] Follow local work in anticipation of drafting intervention 2 next cycle.

**Clubs**
- [x] Facilitate local session on 4/11/16.

**IPPD**
- [x] Participate on second office hours call.
- [x] Follow-up on Discourse prompts.

**NWP**
- [x] Participate in online badge group meeting.
- [x] Draft a faciitation badge ahead of the next meeting.

**Trainings**
- [x] Co-facilitate internal ~~training~~ briefing on web lit workshop materials.
- [x] Draft 2-day training agenda.

**Community**
- [x] Facilitate [April 12th episode](https://github.com/mozilla/learning-networks/issues/368) check-in.
- [x] Create outro script with @KGorr.
- [x] Co-host April 12th episode.
- [x] Follow title slide and music sourcing work on the education participation repo.
- [x] Post production: gif-ify document history, extract podcast, blog, and send thank-you notes.
- [x] Begin planning May 10th youth civic engagement episode.

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by chadsansing** [comment]
Arriving from [#362](https://github.com/mozilla/learning-networks/issues/362).

**Comment by chadsansing** [comment]
Going to https://github.com/mozilla/learning-networks/issues/388.
