### ISSUE TITLE
[Meta] Curriculum work, 4/18/16 - 4/29/16

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#388]
# **Meta**
- [x] Close previous tracking ticket.
- [x] Draft next tracking [Meta] issue.

**Web Literacy Curriculum**
- [x] Revise Intermediate Web Lit II: Storytelling with Scripts materials according to Discourse, GitHub testing feedback.
- [x] Create Intermediate Web Lit II content doc.
- [x] Ship Intermediate Web Lit II content doc to @hannahkane or work with @mmmavis in London to file it as a PR on /teach.

**Open Leadership Curriculum**
- [x] Get to work sprint in DC, 4/18-4/20.
- [ ] Complete draft with @zee-moz.
- [ ] File design brief with @zee-moz.
- [ ] Hand off draft to production with @zee-moz.

**Kenya DSO**
- [ ] Scope and draft internevention 2 with @secretrobotron and @LauraReynal.

**Clubs**
- [x] Facilitate local session on 4/25/16.

**IPPD**
- [ ] ~~Debrief after celebration.~~

**NWP**
- [x] Facilitate coding discussion with Tar River Writing Project (TRWP) cohort.

**Library Journal Code Your Library series**
- [x] Plan and draft presentation on Sustaining Yourself and Your Community.

**Trainings**
- [x] Scope and sequence rp6 agenda with @anmechung, @jvallera, and @hannahkane.
- [x] Scope and sequence IMLS kick-off agenda with @anmechung.

**Community**
- [x] Plan May 10th MCW episode with @amirad, @ohnopauloh, @KGorr, and @ldecoursy.
- [ ] Plan June 14th MCW episode from London @amirad, @ohnopauloh, @KGorr, and @ldecoursy.
- [x] Investigate podcast channel for learning hub comm with @KGorr, and @ldecoursy.

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by chadsansing** [comment]
Arriving from https://github.com/mozilla/learning-networks/issues/376.

**Comment by chadsansing** [comment]
Heading to https://github.com/mozilla/learning-networks/issues/395.
