### ISSUE TITLE
[Meta] Curriculum Work, 5/2/16 - 5/13/16

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#395]
**Meta**
- [x] Close previous tracking ticket.
- [x] Draft next tracking [Meta] issue.

**Web Literacy Curriculum**
- [x] Revise Intermediate Web Lit II: Storytelling with Scripts.
- [x] Share Intermediate Web Lit II to Clubs FB group for testing.
- [x] Determine when to go live on /activities.

**Leadership Curriculum**
- [x] Revise according to incoming feedback.
- [x] Work with Production on A/V assets.

**Kenya DSO**
- [ ] Scope and draft intervention 2.

**LRNG**
- [x] Loop back with @ldecoursy and @chrislarry33 re: updates to the platform and our content.
- [x] Loop back with LRNG re: content updates.

**NWP**
- [x] Attend online New Pathways/badging meeting.

**Library Journal Code Your Library series**
- [x] Run slide deck and notes past @KGorr and @ldecoursy.
- [x] Revise slide deck and notes with internal feedback and feedback from SLJ.
- [x] Online A/V test on 5/2.
- [x] Present on 5/11.

**Trainings**
- [x] Plan rp6 agenda w/ facilitation group.
- [x] Develop IMLS agenda w/ @anmechung.

**Community**
- [x] Confirm guests for May 10th MCW episode.
- [x] Send survey email.
- [x] Get site updated.
- [x] Facilitate run-through meeting.
- [x] Co-host May 10th episode.
- [x] Work on .gif and podcast in post-production.
- [ ] Work w/ @secretrobotron on podcast channel.

**Comment by chadsansing** [comment]
Arriving from https://github.com/mozilla/learning-networks/issues/388.

**Comment by chadsansing** [comment]
Heading to #406.
