### ISSUE TITLE
[Meta] Curriculum work, 5/16/16 - 5/27/16

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#406]
**Meta**
- [x] Close previous tracking ticket.
- [x] Draft next tracking [Meta] issue.

**Web Literacy Curriculum & Trainings**
- [x] Continue to develop IMLS kick-off workshop.
- [x] Continue to develop RP/6 two-day workshop.
- [x] Continue to develop Color Picker Snake Game.
- [x] Migrate workshop materials into updated template.
- [x] Help migrate old lo-fi, no-fi activities into updated template, modules.
- [x] Help migrate old web lit activities into updated template.

**Leadership Curriculum**
- [x] Revise according to incoming feedback.
- [x] Check in w/ Design re: illustrations, template, and treatments.
- [x] Confirm initial video contributors and ship them design briefs.
- [x] Facilitate deep dive on team call.

**Kenya DSO**
- [x] Draft Intervention 2.
- [x] Join community and software group calls.

**LRNG**
- [x] Publish badges/XPs.

**Fund for Openness Grant**
- [x] Consult on application materials.

**Badges**
- [x] Sync up with Matt Rogers of DigitalMe.

**MozFest**
- [x] Participate as consult on learning space planning.
- [x] Explore potential involvement as Pathway Coordinator.

**Community**
- [x] Begin planning June 2016 MCW episode.
- [x] Settle on a time and date for London broadcast.
- [x] Participate on Gigabit community call.
- [x] Help plan & participate in  #TTWchat.

[Back to issues](https://github.com/mozilla/learning-networks/issues)

**Comment by chadsansing** [comment]
Arriving from #395.

**Comment by chadsansing** [comment]
Headed to #410.
