### ISSUE TITLE
[Meta] Curriculum work, 5/30/16 - 6/10/16

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#410]
**Meta**
- [x] Close previous tracking ticket.
- [ ] Draft next tracking [Meta] issue.
- [x] Prep for all-hands.

**Web Literacy**
- [x] Final prep for 6/7/16 IMLS kick-off.
- [x] Get to Chicago on 6/6/16.
- [x] Ship Color Picker Snake Game MVP.
- [ ] Create activity/module around Color Picker Snake Game/interactive media.
- [x] Start designing and building next web lit game.
- [x] Check in on Web Literacy Leaders progress.
- [ ] Assemble team for critical web literacy module development in July.

**Leadership Curriculum**
- [x] Revise modules.
- [x] Consult on final diagram and illustration designs, template treatments.
- [x] Embed diagrams and illustrations in modules.
- [ ] Embed community videos.
- [ ] Migrate the modules to be tested in London into templates.

**Kenya DSO**
- [x] Revise Intervention 2.
- [ ] Participate on community, curriculum, and software group calls.
- [ ] Consult on Intervention 3 (software).

**Badges**
- [ ] Set up a digital literacy chat with LRNG for after all-hands.
- [x] Check in with Matt Rogers from Digital Me re: partnership strategy.
- [x] Help plan for piloting internal badge work through web lit trainings.
- [x] Scope future NWP New Pathways work.

**MozFest**
- [x] Coordinate Mozilla Arcade proposal work with Robert Friedman.

**Community**
- [x] Send invites for June 16th, 2016, MCW episode.
- [x] Confirm guests.
- [x] Update MCW landing page.
- [ ] Consult on Pontiac, MI, summer hackathon planning.

**Comment by chadsansing** [comment]
Arriving from #406.

**Comment by chadsansing** [comment]
Back from All-Hands. New issue soon.

**Comment by chadsansing** [comment]
Headed to #415.
