### ISSUE TITLE
[Meta] Curriculum work, 6/20/16 - 7/2/16

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#415]
**Meta**
- [x] Close previous tracking ticket.
- [x] Draft next tracking [Meta] issue.

**Web Literacy**
- [x] Meet w/ LAMP re: new Mediabreaker launch.
- [ ] Asemble critical web lit module team.
- [x] Work on Color Picker Snake Game instructional materials.
- [ ] Develop Bridge Builder and instructional materials.
- [x] Write-up 'What if they had the web?' game.

**Leadership Curriculum**
- [x] Revise modules based on all-hands feedback.
- [x] Edit and embed convenings video(s).
- [ ] Figure out a leadership curriculum template.

**Kenya DSO**
- [x] Review Intervention 2 feedback.
- [x] Sketch a wifi router gif.
- [x] Participate on community, curriculum, and software group calls.
- [x] Consult on Intervention 3.

**Badges**
- [x] Schedule and facilitate a meeting to review Read badges from DigitalMe.

**MozFest**
- [x] Draft blog post in support of CFP for 'Demystify the Web.'

**Community**
- [x] Spin-up July 12th episode on brokering web literacy around the world.

[Back to issues.](https://github.com/mozilla/learning-networks/issues/)

**Comment by chadsansing** [comment]
Arriving from #410.

**Comment by chadsansing** [comment]
Headed over to #417.
