### ISSUE TITLE
[Meta] Curriculum work, 7/5/16 - 7/15/16

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#417]
**Meta**
- [x] Close previous tracking ticket.
- [ ] Draft next tracking [Meta] issue.

**Web Literacy**
- [ ] Schedule and facilitate a critical web literacy module co-design group meeting.
- [ ] Develop bridge builder game.
- [ ] Finalize agendas and monitor attendance for August web lit trainings.

**Leadership Curriculum**
- [ ] Finish content MVP by July 20th.
- [ ] Revise modules according to feedback from our second round of readers.
- [x] Work with production to develop a template and landing page.

**Kenya DSO**
- [x] Develop Intervention 4.
- [ ] Develop curriculum guidelines blog post.

**Badges**
- [x] Monitor web literacy skills badge development.

**MozFest**
- [x] Revise and submit proposals.
- [x] Begin scorping cross-space and cross-session connections.

**Community**
- [x] Check-in ahead of July 12th episode for final planning.
- [x] Co-host July 12th episode.
- [x] Support post-production work.
- [ ] Facilitate "take-over" episode in August.
- [x] Talk with CV2/NexMap about digital notebooking opportunities at MozFest and a civic data hack day.

[Back to issues](https://github.com/mozilla/learning-networks/issues)

**Comment by chadsansing** [comment]
Arriving from #415.

**Comment by chadsansing** [comment]
Realizing many items have pieces that fall outside the scope of this window of time. Will revisit after PTO.
